#!/usr/bin/env python3
"""memory_recall.py — UserPromptSubmit hook: deterministic per-prompt memory recall.

This Claude Code setup has no native per-file semantic recall — memory arrives ONLY via the whole-file
MEMORY.md startup injection (verified 2026-07-29: 0/3 description-match probes fired). This hook rebuilds
recall on top of the memory keyword index: it matches the user's prompt against each active, non-hot-tier
memory's keywords (from `knowledge/_MEMORY_RECALL.tsv`, generated by build_index.sh) and, on a CONFIDENT
match, injects a compact pointer block so the model knows which `memory/*.md` to open — without whole-loading
them. On UserPromptSubmit, stdout (exit 0) is added to the prompt context (same channel as session_start_routing.sh).

Precision (noise control): a memory surfaces only on a STRONG hit — a multi-word keyword phrase, or a single
keyword ≥6 chars, present at a word boundary — OR ≥2 keyword hits. Tokens <4 chars never match. Hot-tier
memories (already always-loaded) are excluded at generation time. Silent when nothing matches or the prompt
is a harness re-invocation (task notifications, tool pings, bare reminders). Non-blocking: any error prints
nothing and exits 0, so it can never interfere with a prompt.
"""
import json, os, re, sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
TSV = os.path.join(ROOT, "knowledge", "_MEMORY_RECALL.tsv")
MAX = 4                      # cap surfaced memories per prompt
DESC_CAP = 160              # truncate a long description in the pointer line
SKIP_MARKERS = ("task-notification", "toolu_", "<system-reminder", "<local-command", "<command-name",
                "has completed", "background task", "stdout of the background")


def main():
    try:
        raw = sys.stdin.read()
        prompt = (json.loads(raw).get("prompt") or "").strip() if raw.strip() else ""
        if not prompt or not os.path.exists(TSV):
            return 0
        low = " " + prompt.lower() + " "
        if any(m in low for m in SKIP_MARKERS):      # a harness re-invocation, not a real user request
            return 0
        hits = []
        for line in open(TSV, encoding="utf-8"):
            parts = line.rstrip("\n").split("\t")
            if len(parts) != 3:
                continue
            stem, desc, kws = parts
            n, strong = 0, False
            for kw in kws.split("|"):
                kw = kw.strip().lower()
                if len(kw) < 4:
                    continue
                # word-boundary match on alnum so "ds19" ≠ "ds190" and "cap" never fires inside "capable"
                if re.search(r"(?<![a-z0-9])" + re.escape(kw) + r"(?![a-z0-9])", low):
                    n += 1
                    if " " in kw or len(kw) >= 6:
                        strong = True
            if n >= 2 or (n >= 1 and strong):
                hits.append((n, stem, desc))
        if not hits:
            return 0
        hits.sort(key=lambda x: -x[0])
        out = ["[memory-recall] Possibly relevant stored memories (NOT loaded — open the file if useful):"]
        for _n, stem, desc in hits[:MAX]:
            d = desc if len(desc) <= DESC_CAP else desc[:DESC_CAP - 3] + "..."
            out.append(f"- knowledge/memory/{stem}.md — {d}")
        print("\n".join(out))
    except Exception:
        pass  # never interfere with the prompt
    return 0


if __name__ == "__main__":
    sys.exit(main())
