#!/usr/bin/env bash
# build_kit_manifest.sh — generate the AI Workflow Kit component inventory FROM the actual files.
# Kills doc drift (the "7 hooks here, 9 there" problem): the component list is never hand-typed again.
# Idempotent: same repo in -> byte-identical documentation/ai_workflow_kit/COMPONENTS.md out (no timestamps).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

python3 - "$ROOT" <<'PY'
import json, os, re, sys
root = sys.argv[1]
CL = ".claude"

def first_doc(path):
    """A one-line description from a script: python module docstring first line, else first '# ' comment."""
    try:
        lines = open(path, encoding="utf-8").read().split("\n")
    except Exception:
        return ""
    # python docstring
    for i, l in enumerate(lines[:8]):
        s = l.strip()
        m = re.match(r'^[ru]?"""(.*)', s)
        if m:
            inner = m.group(1).strip()
            if inner and not inner.endswith('"""'):
                # take up to the first ' — ' second-clause or the whole first line
                return re.sub(r'\.$', '', inner.split(". ")[0]).strip().strip('"')
            # docstring opens; description on the next non-empty line
            for l2 in lines[i+1:i+4]:
                if l2.strip():
                    return re.sub(r'\.$', '', l2.strip().split(". ")[0]).strip()
    # first block of consecutive non-shebang comment lines (joined — headers often wrap)
    buf = []
    for l in lines[:10]:
        s = l.strip()
        if s.startswith("#") and not s.startswith("#!"):
            buf.append(re.sub(r'^#+\s*', '', s))
        elif buf:
            break
        elif s and not s.startswith("#!"):
            break
    return " ".join(buf).strip()

def fm(path):
    """Parse leading YAML front-matter (scalars + folded multi-line description) → dict."""
    try:
        lines = open(path, encoding="utf-8").read().split("\n")
    except Exception:
        return {}
    if not lines or lines[0].strip() != "---":
        return {}
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return {}
    d, i = {}, 1
    while i < end:
        m = re.match(r"^(\w[\w-]*):\s*(.*)$", lines[i])
        if m:
            k, v = m.group(1), m.group(2).strip()
            if v in (">-", ">", "|", "|-", ""):   # folded/blocked scalar → gather indented continuation
                buf = []
                j = i + 1
                while j < end and (lines[j].startswith("  ") or not lines[j].strip()):
                    if lines[j].strip():
                        buf.append(lines[j].strip())
                    j += 1
                d[k] = " ".join(buf); i = j; continue
            d[k] = v.strip('"').strip("'")
        i += 1
    return d

def one_sentence(s, n=150):
    s = re.sub(r"\s+", " ", s or "").strip()
    s = s.replace("...", "…")                   # keep ellipses from triggering a sentence split
    # drop a redundant leading "name.py — " / "name.sh: " / "Event(Bash) — " prefix (the table already names it)
    s = re.sub(r'^[\w.-]+\.(?:sh|py)\s*[—:-]\s*', '', s)
    s = re.sub(r'^(?:PreToolUse|PostToolUse|UserPromptSubmit|SessionStart|Stop)[^—:-]*[—:-]\s*', '', s)
    # first sentence: a period+space where the period follows a word/closing char (not an abbrev dot run)
    s = re.split(r'(?<=[A-Za-z0-9)\]`"])\.\s', s)[0].rstrip(".")
    if len(s) > n:                              # truncate on a word boundary, not mid-token
        s = s[:n].rsplit(" ", 1)[0].rstrip(" ,;(") + "…"
    return s

out = ["<!-- GENERATED by scripts/build_kit_manifest.sh — do not edit by hand. -->",
       "# AI Workflow Kit — Components (generated inventory)", "",
       "Every hook, script, skill, and agent, read straight from the files. This is the drift-proof",
       "source of truth for the component counts (regenerate with `.claude/scripts/build_kit_manifest.sh`).", ""]

# ---- Hooks (from settings.json registration + each hook's header) ----
settings = json.load(open(os.path.join(root, CL, "settings.json")))
hk = settings.get("hooks", {})
rows, nhooks = [], 0
for event in ("PreToolUse", "PostToolUse", "UserPromptSubmit", "SessionStart", "Stop"):
    for group in hk.get(event, []):
        matcher = group.get("matcher", "")
        for h in group.get("hooks", []):
            cmd = h.get("command", "")
            m = re.search(r'([\w.-]+\.(?:sh|py))', cmd)
            if not m:
                continue
            script = m.group(1)
            p = os.path.join(root, CL, "hooks", script)
            # "can block" = a REAL `exit 2` statement (not the string inside a toggle comment)
            has_block = os.path.exists(p) and re.search(r'(?m)^[^#\n]*\bexit\s+2\b', open(p, encoding="utf-8").read())
            blocks = "yes (exit 2)" if has_block else "no"
            rows.append((event, matcher or "—", script, one_sentence(first_doc(p)), blocks))
            nhooks += 1
out += [f"## Hooks ({nhooks})", "",
        "| event | matcher | script | what it does | can block? |",
        "|-------|---------|--------|--------------|------------|"]
for e, mt, s, d, b in rows:
    out.append(f"| {e} | {mt} | `{s}` | {d} | {b} |")
out.append("")

# ---- Scripts (.claude/scripts) ----
sdir = os.path.join(root, CL, "scripts")
scripts = sorted(f for f in os.listdir(sdir) if f.endswith((".sh", ".py")) and not f.startswith("_"))
out += [f"## Scripts ({len(scripts)})", "", "| script | what it does |", "|--------|--------------|"]
for f in scripts:
    out.append(f"| `{f}` | {one_sentence(first_doc(os.path.join(sdir, f)))} |")
out.append("")

# ---- Skills (.claude/skills/*/SKILL.md) ----
kdir = os.path.join(root, CL, "skills")
skills = sorted(d for d in os.listdir(kdir) if os.path.isdir(os.path.join(kdir, d)))
out += [f"## Skills ({len(skills)})", "", "| skill | description |", "|-------|-------------|"]
for d in skills:
    f = fm(os.path.join(kdir, d, "SKILL.md"))
    out.append(f"| `/{f.get('name', d)}` | {one_sentence(f.get('description',''))} |")
out.append("")

# ---- Agents (.claude/agents/*.md) ----
adir = os.path.join(root, CL, "agents")
agents = sorted(f for f in os.listdir(adir) if f.endswith(".md")) if os.path.isdir(adir) else []
out += [f"## Agents ({len(agents)})", "", "| agent | description |", "|-------|-------------|"]
for f in agents:
    d = fm(os.path.join(adir, f))
    out.append(f"| `{d.get('name', f[:-3])}` | {one_sentence(d.get('description',''))} |")
out.append("")

# ---- Generated indexes (the retrieval surface build_index.sh maintains) ----
idx = ["knowledge/INDEX.md", "knowledge/_ROUTING.md", "knowledge/_MEMORY_INDEX.md",
       "knowledge/_MEMORY_LIFECYCLE.md", "knowledge/_MEMORY_RECALL.tsv", "knowledge/bq/_CATALOG_INDEX.md",
       "knowledge/bq/_TOPICS.md", "knowledge/bq/_COVERAGE.md", "knowledge/decisions/INDEX.md",
       "knowledge/runbooks/INDEX.md", "tickets/INDEX.md"]
out += [f"## Generated indexes ({len(idx)})", "",
        "All regenerated idempotently by `.claude/scripts/build_index.sh` from doc front-matter:", ""]
out += [f"- `{p}`" for p in idx]
out.append("")

dst = os.path.join(root, "documentation", "ai_workflow_kit")
os.makedirs(dst, exist_ok=True)
open(os.path.join(dst, "COMPONENTS.md"), "w", encoding="utf-8").write("\n".join(out).rstrip() + "\n")
print(f"wrote documentation/ai_workflow_kit/COMPONENTS.md — {nhooks} hooks, {len(scripts)} scripts, "
      f"{len(skills)} skills, {len(agents)} agents")
PY
