#!/usr/bin/env bash
# workflow_audit.sh — deterministic signal aggregator for the weekly System-retro loop.
#
# Runs every read-only check in the kit and prints ONE structured markdown rollup to stdout
# (also written to claude-prompts/workflow_audits/signals_latest.md, gitignored working file).
# This is the DETERMINISTIC FLOOR only — it detects/measures/prints, it NEVER edits or deletes.
# The reasoning + propose-only action list is added on top by the /workflow-audit skill (an agent).
#
# Environment-aware: the request log (knowledge/.request_log.jsonl) is gitignored and local-only,
# so on a fresh cloud checkout the request-mining section is marked SKIPPED. The perf log is
# git-tracked, so perf-drift mining runs everywhere.
#
# Never fails the caller: every check is wrapped so one broken check can't abort the routine.
# Usage: workflow_audit.sh            # full rollup to stdout
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SCRIPTS="$ROOT/.claude/scripts"
OUTDIR="$ROOT/claude-prompts/workflow_audits"
mkdir -p "$OUTDIR"
SIGNALS="$OUTDIR/signals_latest.md"
DATE="$(date +%Y-%m-%d)"
PY="python3"

# run a check, never let it abort the script; label failures instead of dying
run() { "$@" 2>&1 || echo "  (check errored — non-fatal; see above)"; }
have() { [ -f "$1" ]; }

# --- detect environment: is the local-only request log present? ---
REQLOG="$ROOT/knowledge/.request_log.jsonl"
if have "$REQLOG"; then ENV_KIND="local (request log present)"; else ENV_KIND="fresh checkout / cloud (request log absent — request-mining skipped)"; fi

{
echo "# Workflow Audit — deterministic signals — $DATE"
echo
echo "- **Branch:** $(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null)  ·  **HEAD:** $(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null)"
echo "- **Environment:** $ENV_KIND"
echo "- Generated by \`.claude/scripts/workflow_audit.sh\` — read-only. Reasoning layer added by \`/workflow-audit\`."
echo

# ── 1. Structure conformance vs folder_definitions.md ──────────────────────────
echo "## 1. Structure conformance (audit_structure.py)"
echo '```'
if have "$SCRIPTS/audit_structure.py"; then
  run $PY "$SCRIPTS/audit_structure.py" --json "$OUTDIR/.structure_findings.json" | tail -40
else echo "audit_structure.py not found"; fi
echo '```'
echo

# ── 2. Ticket + framing-gate adherence ─────────────────────────────────────────
echo "## 2. Ticket / framing-gate adherence (lint_tickets.py)"
echo '```'
if have "$SCRIPTS/lint_tickets.py"; then
  # capture summary line + a sample of offenders (violations first, then warns)
  run $PY "$SCRIPTS/lint_tickets.py" --check | { grep -E "VIOLATION|lint_tickets --check:" || true; }
  echo "--- sample warnings (framing/legacy) ---"
  run $PY "$SCRIPTS/lint_tickets.py" --check | { grep "WARN" | head -8 || true; }
else echo "lint_tickets.py not found"; fi
echo '```'
echo

# ── 3. Knowledge-base health (staleness / orphans / dup-title / capture age) ────
echo "## 3. Knowledge-base health (health_scorecard.py)"
echo '```'
if have "$SCRIPTS/health_scorecard.py"; then
  run $PY "$SCRIPTS/health_scorecard.py" --verbose
else echo "health_scorecard.py not found"; fi
echo '```'
echo

# ── 4. Catalog coverage + documentation debt ───────────────────────────────────
echo "## 4. Catalog coverage & doc debt"
echo '```'
COV="$ROOT/knowledge/bq/_COVERAGE.md"
UNDOC="$ROOT/knowledge/bq/_UNDOCUMENTED.queue"
if have "$COV"; then
  echo "Coverage states (_COVERAGE.md):"
  { grep -iE "skeleton|enriched|verified|stale" "$COV" | head -12 || true; }
else echo "_COVERAGE.md not found"; fi
if have "$UNDOC"; then
  n=$(grep -cvE '^\s*$|^\s*#' "$UNDOC" 2>/dev/null || echo 0)
  echo "Undocumented-table queue: $n entr(y/ies)"
fi
echo '```'
echo

# ── 5. Perf drift (git-tracked log → runs everywhere) ──────────────────────────
echo "## 5. Perf drift — expensive / repeated queries (perf_digest.py)"
echo '```'
if have "$SCRIPTS/perf_digest.py"; then
  echo "--- top cost offenders ---"
  run $PY "$SCRIPTS/perf_digest.py" --mode offenders --top 8 | head -25
  echo "--- repeated query shapes (dedup/cache candidates) ---"
  run $PY "$SCRIPTS/perf_digest.py" --mode repeats --top 8 | head -25
else echo "perf_digest.py not found"; fi
echo '```'
echo

# ── 6. Request patterns (LOCAL-ONLY — gitignored log) ──────────────────────────
echo "## 6. Request patterns → /skill candidates (request_digest.py)"
echo '```'
if have "$REQLOG" && have "$SCRIPTS/request_digest.py"; then
  run $PY "$SCRIPTS/request_digest.py" --min 3
else
  echo "SKIPPED — request log is gitignored/local-only and absent in this environment."
  echo "Run '/workflow-audit requests' on the local Mac to mine request patterns."
fi
echo '```'
echo

# ── 7. Git hygiene ─────────────────────────────────────────────────────────────
echo "## 7. Git hygiene"
echo '```'
dirty=$(git -C "$ROOT" status --porcelain 2>/dev/null | wc -l | tr -d ' ')
echo "Uncommitted/untracked entries: $dirty"
git -C "$ROOT" status --porcelain 2>/dev/null | head -12
echo '```'
echo

# ── 8. Standards drift — skills/scripts not referenced in CLAUDE.md ────────────
echo "## 8. Standards drift (skills/scripts vs CLAUDE.md references)"
echo '```'
CLAUDEMD="$ROOT/.claude/CLAUDE.md"
GLOBALMD="$HOME/.claude/CLAUDE.md"
for d in "$ROOT/.claude/skills"/*/ ; do
  [ -d "$d" ] || continue
  s=$(basename "$d")
  if ! { grep -qi "$s" "$CLAUDEMD" 2>/dev/null || grep -qi "$s" "$GLOBALMD" 2>/dev/null; }; then
    echo "skill '$s' not referenced in either CLAUDE.md — confirm it's documented"
  fi
done
echo "(scripts present: $(ls "$SCRIPTS" 2>/dev/null | wc -l | tr -d ' '))"
echo '```'
echo

# ── 9. Signal-file backlog → prune candidates ──────────────────────────────────
# The Pi commits one signals_<date>.md every week; once a reasoned audit_<date>.md exists the raw
# signals file is superseded. Keep the newest KEEP, flag older ones as prune candidates (Tier 1 Safe).
echo "## 9. Signal-file backlog (weekly signals_*.md → prune candidates)"
echo '```'
KEEP=8
sigs=$(ls -1 "$OUTDIR"/signals_20*.md 2>/dev/null | sort)
n=$(printf '%s\n' "$sigs" | grep -c .)
echo "signals_*.md on disk: $n (policy: keep newest $KEEP; reasoned audit_*.md reports are kept regardless)"
if [ "$n" -gt "$KEEP" ]; then
  prune=$((n - KEEP))
  old=$(printf '%s\n' "$sigs" | head -n "$prune" | sed "s#^$ROOT/##")
  echo "PRUNE CANDIDATES ($prune oldest, superseded by reasoned reports):"
  printf '%s\n' "$old" | sed 's/^/  /'
  echo "ready command: git rm $(printf '%s' "$old" | tr '\n' ' ')"
else
  echo "under retention cap ($n/$KEEP) — no pruning needed."
fi
echo '```'
echo

# ── 10. Memory health (knowledge/memory/*.md — the unified auto-memory layer) ──
# Key-free + git-tracked, so the Pi cron captures it weekly like every other signal. Lifecycle rollup,
# refresh queue, near-duplicate merge candidates, unresolved wikilinks, MEMORY.md hot-tier budget.
echo "## 10. Memory health (health_scorecard.py --memory)"
echo '```'
if have "$SCRIPTS/health_scorecard.py"; then
  run $PY "$SCRIPTS/health_scorecard.py" --memory
else echo "health_scorecard.py not found"; fi
if have "$SCRIPTS/lint_memory.py"; then
  echo "--- unindexed / broken (lint_memory --check) ---"
  run $PY "$SCRIPTS/lint_memory.py" --check 2>&1 | { grep -E "VIOLATION|WIKILINK|--check:" || true; }
fi
echo '```'
echo

echo "---"
echo "_End of deterministic signals. The /workflow-audit skill turns these into a prioritized, propose-only action list._"
} | tee "$SIGNALS"
