"""Event-log parser + run-detector tests.

The parser test runs on a REAL Spark event log committed as a fixture (generated by
tests/fixtures/gen_eventlog.py). The detector tests craft SparkRun objects to exercise the
infra/failure recommendation types the tiny fixture doesn't trigger.
"""

from __future__ import annotations

import os

import pytest

from airflow_optimizer.eventlog import ExecutorInfo, SparkRun, StageMetrics, parse_eventlog
from airflow_optimizer.optimizations import analyze_run

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "eventlog.zstd")
CACHE_FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "eventlog_cache.zstd")


def test_parse_real_eventlog_all_surfaces() -> None:
    """The parser extracts every surface from a real event log: config, stages, executors, SQL."""
    run = parse_eventlog(FIXTURE)
    assert run.jobs >= 3
    assert run.spark_props.get("spark.sql.shuffle.partitions") == "8"  # environment surface
    assert run.executors  # executor surface
    # stage surface: shuffle read of a stage equals shuffle write of its producer (correctly aggregated)
    assert any(s.shuffle_write_bytes > 0 for s in run.stages)
    assert any(s.input_bytes > 0 for s in run.stages)
    # the intentional 80%-single-key skew is caught (invisible in the plan text)
    assert max(s.skew_ratio for s in run.stages) >= 5
    # SQL surface: per-node operator metrics recovered from sparkPlanInfo + accumulables
    assert any(s.node_metrics for s in run.sql)
    assert any("number of output rows" in m["metrics"] or "duration" in m["metrics"]
               for s in run.sql for m in s.node_metrics)


def test_parse_storage_surface_real() -> None:
    """The storage surface (cached RDD blocks + bytes) is recovered from BlockUpdated events."""
    run = parse_eventlog(CACHE_FIXTURE)
    assert run.rdd_cached_blocks > 0
    assert run.cached_rdd_bytes > 0


def test_detectors_flag_skew_on_real_run(monkeypatch: pytest.MonkeyPatch) -> None:
    """analyze_run surfaces the skew as a code-type finding on the real log."""
    import airflow_optimizer.optimizations as opt

    monkeypatch.setattr(opt, "SKEW_MIN_TASK_MS", 0)  # tiny fixture; plumbing not thresholds
    findings = analyze_run(parse_eventlog(FIXTURE))
    assert any(f.key == "skew" and f.rec_type == "code" for f in findings)


def test_infra_and_failure_recommendation_types() -> None:
    """A crafted run exercises the infra (GC, spot) and failure (fetch) recommendation types."""
    run = SparkRun(spark_props={"spark.sql.shuffle.partitions": "200"}, rdd_evictions=5,
                   cached_rdd_bytes=40 * 1024**3)
    run.stages = [
        StageMetrics(stage_id=1, num_tasks=100, run_time_ms=100_000, gc_time_ms=30_000,
                     fetch_failed=12, mem_spill=40 * 1024**3),
    ]
    run.executors = [ExecutorInfo(exec_id="2", removed_reason="spot instance preemption",
                                  failed_tasks=168)]
    keys = {(f.key, f.rec_type) for f in analyze_run(run)}
    assert ("gc_pressure", "infra") in keys
    assert ("spot_preemption_cost", "infra") in keys
    assert ("shuffle_fetch_instability", "failure") in keys
    assert ("disk_spill", "code") in keys
    assert ("cache_ineffective", "infra") in keys


def test_straggler_vs_data_skew_discrimination() -> None:
    """Duration skew on uniform data = straggler (infra/speculation), not data skew (code)."""
    uniform_reads = [100] * 19 + [110]
    straggler_stage = StageMetrics(stage_id=6, num_tasks=20,
                                   task_durs=[30_000] * 19 + [600_000],
                                   task_read_bytes=uniform_reads)
    skewed_stage = StageMetrics(stage_id=7, num_tasks=20,
                                task_durs=[30_000] * 19 + [600_000],
                                task_read_bytes=[100] * 19 + [5000])
    run = SparkRun(spark_props={"spark.speculation": "false"},
                   stages=[straggler_stage, skewed_stage])
    by_key = {(f.key, f.rec_type) for f in analyze_run(run)}
    assert ("straggler", "infra") in by_key
    assert ("skew", "code") in by_key
    straggler = next(f for f in analyze_run(run) if f.key == "straggler")
    assert "speculation is OFF" in straggler.evidence


def test_idle_reserved_executors_detector() -> None:
    """A fleet held with <40% slot utilization emits the idle_reserved_executors finding."""
    t0, t1 = 1_000_000_000_000, 1_000_000_000_000 + 3 * 3_600_000  # 3h app
    execs = [ExecutorInfo(exec_id=str(i), added_ts=t0, run_time_ms=1 * 3_600_000)
             for i in range(10)]  # 30 exec-h held, 10 busy -> 33% util
    run = SparkRun(spark_props={"spark.executor.cores": "1",
                                "spark.dynamicAllocation.shuffleTracking.enabled": "true"},
                   executors=execs, app_end_ts=t1)
    findings = {f.key: f for f in analyze_run(run)}
    assert "idle_reserved_executors" in findings
    assert "shuffleTracking pins executors" in findings["idle_reserved_executors"].evidence


def test_optimize_entrypoint_end_to_end(monkeypatch: pytest.MonkeyPatch) -> None:
    """The one-call entrypoint parses the real log and renders a grouped report."""
    import airflow_optimizer.optimizations as opt
    from airflow_optimizer.optimize import optimize_run, render_report

    monkeypatch.setattr(opt, "SKEW_MIN_TASK_MS", 0)
    findings = optimize_run(FIXTURE)
    assert any(f.key == "skew" for f in findings)
    report = render_report(findings)
    assert "CODE / query-PR" in report
    assert "skew" in report.lower()


def test_parse_v2_rolling_dir_reads_all_parts(tmp_path: os.PathLike[str]) -> None:
    """A v2 rolling dir is parsed across ALL events_* parts, in numeric part order.

    Reading only part 1, or reading parts lexically, silently truncates the run.
    """
    import json
    from pathlib import Path

    tmp_path = Path(tmp_path)

    d = tmp_path / "eventlog_v2_batch-test"
    d.mkdir()
    (d / "appstatus_batch-test").write_text("")
    part_events = {
        "events_1_batch-test": [
            {"Event": "SparkListenerApplicationStart", "App Name": "rolling-test",
             "Timestamp": 1000},
            {"Event": "SparkListenerJobStart"},
        ],
        "events_2_batch-test": [{"Event": "SparkListenerJobStart"}],
        "events_10_batch-test": [
            {"Event": "SparkListenerJobStart"},
            {"Event": "SparkListenerApplicationEnd", "Timestamp": 61000},
        ],
    }
    for name, events in part_events.items():
        (d / name).write_text("\n".join(json.dumps(e) for e in events))

    from airflow_optimizer.eventlog import _part_order

    ordered = sorted(part_events, key=_part_order)
    assert ordered == ["events_1_batch-test", "events_2_batch-test", "events_10_batch-test"]

    run = parse_eventlog(str(d))
    assert run.app_name == "rolling-test"
    assert run.jobs == 3  # one per part - fails if only cand[0] is read
    assert run.duration_ms == 60000  # ApplicationEnd lives in the last part


def test_multiframe_zstd_reads_all_frames(tmp_path: os.PathLike[str]) -> None:
    """Concatenated zstd frames (real Spark logs) parse fully - not just frame 1."""
    import json
    import subprocess
    from pathlib import Path

    tmp_path = Path(tmp_path)
    f1 = json.dumps({"Event": "SparkListenerApplicationStart", "App Name": "mf",
                     "App ID": "app-1", "Timestamp": 1000}) + "\n"
    f2 = json.dumps({"Event": "SparkListenerJobStart"}) + "\n" + json.dumps(
        {"Event": "SparkListenerApplicationEnd", "Timestamp": 3000}) + "\n"
    frames = b""
    for chunk in (f1, f2):
        frames += subprocess.run(["zstd", "-q", "-c"], input=chunk.encode(),
                                 capture_output=True).stdout
    log = tmp_path / "multiframe.zstd"
    log.write_bytes(frames)
    run = parse_eventlog(str(log))
    assert run.app_id == "app-1"  # 'App ID' is the real field name, not 'appId'
    assert run.jobs == 1 and run.duration_ms == 2000  # frame 2 content was read


def test_corrupt_zstd_raises_not_clean(tmp_path: os.PathLike[str]) -> None:
    """An undecodable .zstd surfaces as an error - never an empty 'clean' run."""
    from pathlib import Path

    import pytest

    bad = Path(tmp_path) / "corrupt.zstd"
    bad.write_bytes(b"\x28\xb5\x2f\xfd" + b"garbage-not-a-frame")
    with pytest.raises(ValueError):
        parse_eventlog(str(bad))


def test_stage_retry_attempts_do_not_merge() -> None:
    """A retried stage keeps only its last attempt's metrics (no double-count)."""
    import json

    events = [
        {"Event": "SparkListenerTaskEnd", "Stage ID": 1, "Stage Attempt ID": 0,
         "Task End Reason": {"Reason": "Success"},
         "Task Info": {"Executor ID": "1", "Launch Time": 0, "Finish Time": 100},
         "Task Metrics": {"Executor Run Time": 100,
                          "Shuffle Write Metrics": {"Shuffle Bytes Written": 500}}},
        {"Event": "SparkListenerStageCompleted",
         "Stage Info": {"Stage ID": 1, "Stage Attempt ID": 0, "Number of Tasks": 1,
                        "Failure Reason": "FetchFailed"}},
        {"Event": "SparkListenerTaskEnd", "Stage ID": 1, "Stage Attempt ID": 1,
         "Task End Reason": {"Reason": "Success"},
         "Task Info": {"Executor ID": "1", "Launch Time": 0, "Finish Time": 50},
         "Task Metrics": {"Executor Run Time": 50,
                          "Shuffle Write Metrics": {"Shuffle Bytes Written": 700}}},
        {"Event": "SparkListenerStageCompleted",
         "Stage Info": {"Stage ID": 1, "Stage Attempt ID": 1, "Number of Tasks": 1}},
    ]
    import tempfile

    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
        f.write("\n".join(json.dumps(e) for e in events))
        path = f.name
    run = parse_eventlog(path)
    (st,) = run.stages
    assert st.shuffle_write_bytes == 700  # attempt 0's 500 not summed in
    assert st.succeeded == 1 and st.num_tasks == 1


def test_failed_tasks_do_not_pollute_skew() -> None:
    """A long-running FAILED task must not drive skew/straggler ratios."""
    import json
    import tempfile

    events = []
    for _ in range(8):
        events.append({"Event": "SparkListenerTaskEnd", "Stage ID": 2, "Stage Attempt ID": 0,
                       "Task End Reason": {"Reason": "Success"},
                       "Task Info": {"Executor ID": "1", "Launch Time": 0, "Finish Time": 100},
                       "Task Metrics": {"Executor Run Time": 100}})
    events.append({"Event": "SparkListenerTaskEnd", "Stage ID": 2, "Stage Attempt ID": 0,
                   "Task End Reason": {"Reason": "ExceptionFailure"},
                   "Task Info": {"Executor ID": "1", "Launch Time": 0, "Finish Time": 100000},
                   "Task Metrics": {"Executor Run Time": 100000}})
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
        f.write("\n".join(json.dumps(e) for e in events))
        path = f.name
    (st,) = parse_eventlog(path).stages
    assert st.skew_ratio < 5  # the 1000x failed task is excluded
    assert st.failed == 1


def test_zero_median_ratios_return_one() -> None:
    """A zero median (trivial stage) must not manufacture astronomical skew ratios."""
    st = StageMetrics(stage_id=1, task_durs=[0, 0, 0, 400],
                      task_read_bytes=[0, 0, 0, 345_427])
    assert st.skew_ratio == 1.0
    assert st.data_skew_ratio == 1.0


def test_fleet_crawl_ranks_worst_first(monkeypatch: pytest.MonkeyPatch) -> None:
    """The crawl scans multiple event logs and ranks the one with findings first."""
    import airflow_optimizer.optimizations as opt
    from airflow_optimizer.crawl import crawl, render_crawl

    monkeypatch.setattr(opt, "SKEW_MIN_TASK_MS", 0)
    reports = crawl([FIXTURE, CACHE_FIXTURE])
    assert reports[0].source.endswith("eventlog.zstd")  # the skewed job ranks first
    assert reports[0].n_high >= 1
    assert "Fleet optimization" in render_crawl(reports)


if __name__ == "__main__":
    test_parse_real_eventlog_all_surfaces()
    test_parse_storage_surface_real()
    test_optimize_entrypoint_end_to_end()
    test_detectors_flag_skew_on_real_run()
    test_infra_and_failure_recommendation_types()
    test_fleet_crawl_ranks_worst_first()
    print("OK - eventlog parser + detectors validated on a real Spark event log")
