"""Event-log parser + run-detector tests.

The parser test runs on a REAL Spark event log committed as a fixture (generated by
tests/fixtures/gen_eventlog.py). The detector tests craft SparkRun objects to exercise the
infra/failure recommendation types the tiny fixture doesn't trigger.
"""

from __future__ import annotations

import os

from airflow_debugger.eventlog import ExecutorInfo, SparkRun, StageMetrics, parse_eventlog
from airflow_debugger.optimizations import analyze_run

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "eventlog.zstd")
CACHE_FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "eventlog_cache.zstd")


def test_parse_real_eventlog_all_surfaces() -> None:
    """The parser extracts every surface from a real event log: config, stages, executors, SQL."""
    run = parse_eventlog(FIXTURE)
    assert run.jobs >= 3
    assert run.spark_props.get("spark.sql.shuffle.partitions") == "8"  # environment surface
    assert run.executors  # executor surface
    # stage surface: shuffle read of a stage equals shuffle write of its producer (correctly aggregated)
    assert any(s.shuffle_write_bytes > 0 for s in run.stages)
    assert any(s.input_bytes > 0 for s in run.stages)
    # the intentional 80%-single-key skew is caught (invisible in the plan text)
    assert max(s.skew_ratio for s in run.stages) >= 5
    # SQL surface: per-node operator metrics recovered from sparkPlanInfo + accumulables
    assert any(s.node_metrics for s in run.sql)
    assert any("number of output rows" in m["metrics"] or "duration" in m["metrics"]
               for s in run.sql for m in s.node_metrics)


def test_parse_storage_surface_real() -> None:
    """The storage surface (cached RDD blocks + bytes) is recovered from BlockUpdated events."""
    run = parse_eventlog(CACHE_FIXTURE)
    assert run.rdd_cached_blocks > 0
    assert run.cached_rdd_bytes > 0


def test_detectors_flag_skew_on_real_run() -> None:
    """analyze_run surfaces the skew as a code-type finding on the real log."""
    findings = analyze_run(parse_eventlog(FIXTURE))
    assert any(f.key == "skew" and f.rec_type == "code" for f in findings)


def test_infra_and_failure_recommendation_types() -> None:
    """A crafted run exercises the infra (GC, spot) and failure (fetch) recommendation types."""
    run = SparkRun(spark_props={"spark.sql.shuffle.partitions": "200"}, rdd_evictions=5,
                   cached_rdd_bytes=40 * 1024**3)
    run.stages = [
        StageMetrics(stage_id=1, num_tasks=100, run_time_ms=100_000, gc_time_ms=30_000,
                     fetch_failed=12, mem_spill=30 * 1024**3),
    ]
    run.executors = [ExecutorInfo(exec_id="2", removed_reason="spot instance preemption",
                                  failed_tasks=168)]
    keys = {(f.key, f.rec_type) for f in analyze_run(run)}
    assert ("gc_pressure", "infra") in keys
    assert ("spot_preemption_cost", "infra") in keys
    assert ("shuffle_fetch_instability", "failure") in keys
    assert ("disk_spill", "code") in keys
    assert ("cache_ineffective", "infra") in keys


def test_optimize_entrypoint_end_to_end() -> None:
    """The one-call entrypoint parses the real log and renders a grouped report."""
    from airflow_debugger.optimize import optimize_run, render_report

    findings = optimize_run(FIXTURE)
    assert any(f.key == "skew" for f in findings)
    report = render_report(findings)
    assert "CODE / query-PR" in report
    assert "skew" in report.lower()


def test_fleet_crawl_ranks_worst_first() -> None:
    """The crawl scans multiple event logs and ranks the one with findings first."""
    from airflow_debugger.crawl import crawl, render_crawl

    reports = crawl([FIXTURE, CACHE_FIXTURE])
    assert reports[0].source.endswith("eventlog.zstd")  # the skewed job ranks first
    assert reports[0].n_high >= 1
    assert "Fleet optimization" in render_crawl(reports)


if __name__ == "__main__":
    test_parse_real_eventlog_all_surfaces()
    test_parse_storage_surface_real()
    test_optimize_entrypoint_end_to_end()
    test_detectors_flag_skew_on_real_run()
    test_infra_and_failure_recommendation_types()
    test_fleet_crawl_ranks_worst_first()
    print("OK - eventlog parser + detectors validated on a real Spark event log")
